### ISSUE TITLE
Interesting code-walkthrough design

### ISSUE THREAD

**Issue by jmuchovej** [vpj/vpj.github.com#2]
Less of an issue, more of a question.

How do you get your webpages to sync up the way they do for posts like PPO?

**Comment by spacegoing** [comment]
Thats also the reason I came here!

**Comment by vpj** [comment]
Sorry @ionlights  for some reason I have missed the notification when this issue was opened. And I almost missed the email notification when @spacegoing commented.

I used a program inspired by https://github.com/jashkenas/docco to generate HTML from comments.

But now I'm working on a UI to add annotations which is easier for me: https://github.com/vpj/annotate Let me know your thoughts on this.
